export const data = [
  {
    name: "Lucius Z. Evans",
    screen_name: "Harlan",
    followers_count: 518,
    following_count: 530,
    location: "Quickborn",
    verified: false,
  },
  {
    name: "Calista Soto",
    screen_name: "Magee",
    followers_count: 853,
    following_count: 773,
    location: "Parkland County",
    verified: false,
  },
  {
    name: "Charity Burton",
    screen_name: "Phoebe",
    followers_count: 749,
    following_count: 499,
    location: "Pordenone",
    verified: false,
  },
  {
    name: "Griffin K. Short",
    screen_name: "Maggie",
    followers_count: 131,
    following_count: 340,
    location: "Laives/Leifers",
    verified: true,
  },
  {
    name: "Clare K. Alston",
    screen_name: "Norman",
    followers_count: 549,
    following_count: 110,
    location: "Puyehue",
    verified: true,
  },
  {
    name: "Elmo Gilliam",
    screen_name: "Rae",
    followers_count: 399,
    following_count: 206,
    location: "Acoz",
    verified: false,
  },
  {
    name: "Rooney Saunders",
    screen_name: "Carl",
    followers_count: 722,
    following_count: 830,
    location: "Calle Blancos",
    verified: true,
  },
  {
    name: "Sloane Espinoza",
    screen_name: "Charde",
    followers_count: 469,
    following_count: 772,
    location: "Unecha",
    verified: false,
  },
  {
    name: "Caldwell S. Pena",
    screen_name: "Ava",
    followers_count: 464,
    following_count: 167,
    location: "Chesapeake",
    verified: false,
  },
  {
    name: "Naomi Washington",
    screen_name: "Zane",
    followers_count: 318,
    following_count: 956,
    location: "Neelum Valley",
    verified: false,
  },
  {
    name: "Brenden Cash",
    screen_name: "Fatima",
    followers_count: 788,
    following_count: 608,
    location: "Cercepiccola",
    verified: false,
  },
  {
    name: "Delilah Barton",
    screen_name: "Maggie",
    followers_count: 734,
    following_count: 472,
    location: "Lloydminster",
    verified: false,
  },
  {
    name: "Blythe O. Patterson",
    screen_name: "Porter",
    followers_count: 263,
    following_count: 765,
    location: "Gaziantep",
    verified: false,
  },
  {
    name: "Kato E. Gibson",
    screen_name: "Avram",
    followers_count: 475,
    following_count: 717,
    location: "Long Eaton",
    verified: false,
  },
  {
    name: "Mariam Z. Faulkner",
    screen_name: "Mallory",
    followers_count: 108,
    following_count: 342,
    location: "Spiere-Helkijn",
    verified: false,
  },
  {
    name: "Dexter Parsons",
    screen_name: "Emi",
    followers_count: 255,
    following_count: 671,
    location: "Zhob",
    verified: false,
  },
  {
    name: "Scarlet Stone",
    screen_name: "Rina",
    followers_count: 338,
    following_count: 531,
    location: "Colchester",
    verified: false,
  },
  {
    name: "Hasad O. Battle",
    screen_name: "Yoko",
    followers_count: 448,
    following_count: 847,
    location: "Albany",
    verified: true,
  },
  {
    name: "Bradley M. Griffin",
    screen_name: "Maia",
    followers_count: 499,
    following_count: 770,
    location: "Cuernavaca",
    verified: true,
  },
  {
    name: "Callie William",
    screen_name: "Malachi",
    followers_count: 163,
    following_count: 125,
    location: "Beerse",
    verified: false,
  },
  {
    name: "Norman Zimmerman",
    screen_name: "Hyatt",
    followers_count: 161,
    following_count: 769,
    location: "Samsun",
    verified: true,
  },
  {
    name: "Cody G. Vazquez",
    screen_name: "Hu",
    followers_count: 294,
    following_count: 575,
    location: "Ch‰tillon",
    verified: true,
  },
  {
    name: "Melvin Hawkins",
    screen_name: "Kellie",
    followers_count: 768,
    following_count: 860,
    location: "Adelaide",
    verified: true,
  },
  {
    name: "Yael Page",
    screen_name: "Nigel",
    followers_count: 699,
    following_count: 368,
    location: "Mojokerto",
    verified: false,
  },
  {
    name: "Sloane Ward",
    screen_name: "Buffy",
    followers_count: 134,
    following_count: 714,
    location: "Wedel",
    verified: false,
  },
  {
    name: "Dawn Mckay",
    screen_name: "Pamela",
    followers_count: 983,
    following_count: 659,
    location: "Würzburg",
    verified: false,
  },
  {
    name: "Ulric Douglas",
    screen_name: "Dara",
    followers_count: 521,
    following_count: 281,
    location: "Siegendorf",
    verified: false,
  },
  {
    name: "Ray Tyler",
    screen_name: "Justin",
    followers_count: 990,
    following_count: 205,
    location: "Licantén",
    verified: true,
  },
  {
    name: "Ira S. Pittman",
    screen_name: "Gemma",
    followers_count: 815,
    following_count: 515,
    location: "San Chirico Nuovo",
    verified: false,
  },
  {
    name: "Eric A. Gillespie",
    screen_name: "Rhea",
    followers_count: 712,
    following_count: 832,
    location: "Gatchina",
    verified: false,
  },
  {
    name: "Yoshio Mccullough",
    screen_name: "Buffy",
    followers_count: 594,
    following_count: 181,
    location: "New Sarepta",
    verified: true,
  },
  {
    name: "Jerome Stein",
    screen_name: "Ina",
    followers_count: 802,
    following_count: 836,
    location: "Lesve",
    verified: true,
  },
  {
    name: "Ivor Mitchell",
    screen_name: "Cruz",
    followers_count: 721,
    following_count: 333,
    location: "Fort Good Hope",
    verified: true,
  },
  {
    name: "Ainsley A. Lancaster",
    screen_name: "Joel",
    followers_count: 387,
    following_count: 570,
    location: "Mülheim",
    verified: true,
  },
  {
    name: "Callum O. Chaney",
    screen_name: "Dillon",
    followers_count: 994,
    following_count: 846,
    location: "San Damiano al Colle",
    verified: false,
  },
  {
    name: "Emi Lindsay",
    screen_name: "Sade",
    followers_count: 322,
    following_count: 927,
    location: "Rum",
    verified: false,
  },
  {
    name: "Bryar Y. Ratliff",
    screen_name: "Vielka",
    followers_count: 254,
    following_count: 705,
    location: "Barahanagar",
    verified: true,
  },
  {
    name: "Aiko Q. Keith",
    screen_name: "Mufutau",
    followers_count: 774,
    following_count: 516,
    location: "Meerut Cantonment",
    verified: true,
  },
  {
    name: "Nell Leach",
    screen_name: "Emi",
    followers_count: 452,
    following_count: 332,
    location: "Cumberland",
    verified: false,
  },
  {
    name: "Reed Wong",
    screen_name: "Elmo",
    followers_count: 294,
    following_count: 918,
    location: "Oliver",
    verified: false,
  },
  {
    name: "Gil Z. Adams",
    screen_name: "Jennifer",
    followers_count: 161,
    following_count: 209,
    location: "Ponta Grossa",
    verified: true,
  },
  {
    name: "Jordan U. Cannon",
    screen_name: "Rashad",
    followers_count: 337,
    following_count: 129,
    location: "Busan",
    verified: true,
  },
  {
    name: "James Q. Sweet",
    screen_name: "Penelope",
    followers_count: 951,
    following_count: 604,
    location: "Telfs",
    verified: true,
  },
  {
    name: "Brent I. Patel",
    screen_name: "Rhonda",
    followers_count: 131,
    following_count: 100,
    location: "Naumburg",
    verified: false,
  },
  {
    name: "Samuel N. Nixon",
    screen_name: "Kyra",
    followers_count: 941,
    following_count: 124,
    location: "Medicine Hat",
    verified: true,
  },
  {
    name: "Signe X. Acevedo",
    screen_name: "Deirdre",
    followers_count: 678,
    following_count: 762,
    location: "Pironchamps",
    verified: false,
  },
  {
    name: "Mariam Brown",
    screen_name: "Jordan",
    followers_count: 912,
    following_count: 618,
    location: "Wangaratta",
    verified: true,
  },
  {
    name: "Bradley U. Compton",
    screen_name: "Nina",
    followers_count: 271,
    following_count: 845,
    location: "Igboho",
    verified: false,
  },
  {
    name: "Natalie X. Navarro",
    screen_name: "Evangeline",
    followers_count: 500,
    following_count: 357,
    location: "Sint-Pieters-Kapelle",
    verified: true,
  },
  {
    name: "Josiah P. Howe",
    screen_name: "Jana",
    followers_count: 695,
    following_count: 815,
    location: "Darion",
    verified: true,
  },
  {
    name: "Vernon H. Mathis",
    screen_name: "Alden",
    followers_count: 827,
    following_count: 216,
    location: "Bella",
    verified: false,
  },
  {
    name: "Wynne Merrill",
    screen_name: "Heather",
    followers_count: 856,
    following_count: 720,
    location: "Manokwari",
    verified: false,
  },
  {
    name: "Beverly C. Boyer",
    screen_name: "Kibo",
    followers_count: 726,
    following_count: 133,
    location: "Meeuwen",
    verified: true,
  },
  {
    name: "Carla Bond",
    screen_name: "Macey",
    followers_count: 743,
    following_count: 483,
    location: "Belmonte del Sannio",
    verified: true,
  },
  {
    name: "Candace Y. Simpson",
    screen_name: "Sophia",
    followers_count: 766,
    following_count: 487,
    location: "Verdun",
    verified: false,
  },
  {
    name: "Ori Reed",
    screen_name: "Chaim",
    followers_count: 639,
    following_count: 715,
    location: "Loksbergen",
    verified: true,
  },
  {
    name: "Demetrius L. Pace",
    screen_name: "Alfonso",
    followers_count: 335,
    following_count: 440,
    location: "Laino Castello",
    verified: true,
  },
  {
    name: "Amber Walton",
    screen_name: "Andrew",
    followers_count: 397,
    following_count: 185,
    location: "Cambridge",
    verified: false,
  },
  {
    name: "Buckminster Dominguez",
    screen_name: "Dexter",
    followers_count: 328,
    following_count: 328,
    location: "Ararat",
    verified: false,
  },
  {
    name: "Scott Cherry",
    screen_name: "Kuame",
    followers_count: 272,
    following_count: 533,
    location: "Sevilla",
    verified: true,
  },
  {
    name: "Ryder Knox",
    screen_name: "Amy",
    followers_count: 431,
    following_count: 620,
    location: "Santa Marta",
    verified: true,
  },
  {
    name: "Portia Y. Neal",
    screen_name: "Colorado",
    followers_count: 971,
    following_count: 416,
    location: "Ergani",
    verified: true,
  },
  {
    name: "Gary Ingram",
    screen_name: "Tanek",
    followers_count: 841,
    following_count: 715,
    location: "Krasnaya Yaruga",
    verified: false,
  },
  {
    name: "Gareth T. Gregory",
    screen_name: "Ifeoma",
    followers_count: 629,
    following_count: 814,
    location: "Sneek",
    verified: true,
  },
  {
    name: "Aretha Waller",
    screen_name: "Patrick",
    followers_count: 894,
    following_count: 444,
    location: "El Bosque",
    verified: true,
  },
  {
    name: "Quintessa Davis",
    screen_name: "Wanda",
    followers_count: 191,
    following_count: 860,
    location: "Toowoomba",
    verified: false,
  },
  {
    name: "Halee M. Anthony",
    screen_name: "Harding",
    followers_count: 654,
    following_count: 570,
    location: "Dhanbad",
    verified: true,
  },
  {
    name: "Francesca Mercer",
    screen_name: "Cadman",
    followers_count: 976,
    following_count: 483,
    location: "Weyburn",
    verified: true,
  },
  {
    name: "Jaime Hanson",
    screen_name: "Dylan",
    followers_count: 438,
    following_count: 476,
    location: "Montjovet",
    verified: false,
  },
  {
    name: "Ayanna N. Watkins",
    screen_name: "Warren",
    followers_count: 883,
    following_count: 534,
    location: "Thunder Bay",
    verified: false,
  },
  {
    name: "Erasmus H. Johnson",
    screen_name: "Louis",
    followers_count: 509,
    following_count: 276,
    location: "Caplan",
    verified: true,
  },
  {
    name: "Lyle D. Sykes",
    screen_name: "Colette",
    followers_count: 425,
    following_count: 170,
    location: "Waalwijk",
    verified: false,
  },
  {
    name: "Echo V. Moon",
    screen_name: "Kirsten",
    followers_count: 555,
    following_count: 729,
    location: "Vieux-Genappe",
    verified: true,
  },
  {
    name: "Moses H. Gallegos",
    screen_name: "Abel",
    followers_count: 439,
    following_count: 442,
    location: "Asha",
    verified: false,
  },
  {
    name: "Deborah Q. Tyler",
    screen_name: "Sade",
    followers_count: 859,
    following_count: 207,
    location: "İslahiye",
    verified: true,
  },
  {
    name: "Leah F. Romero",
    screen_name: "Blossom",
    followers_count: 544,
    following_count: 539,
    location: "Colombo",
    verified: false,
  },
  {
    name: "Yen Thompson",
    screen_name: "Linus",
    followers_count: 605,
    following_count: 536,
    location: "Khanewal",
    verified: false,
  },
  {
    name: "Palmer G. Workman",
    screen_name: "Beau",
    followers_count: 490,
    following_count: 728,
    location: "Gallodoro",
    verified: false,
  },
  {
    name: "Alice N. Evans",
    screen_name: "Aphrodite",
    followers_count: 496,
    following_count: 122,
    location: "Candela",
    verified: true,
  },
  {
    name: "Xanthus Howard",
    screen_name: "Amery",
    followers_count: 763,
    following_count: 630,
    location: "San Rafael",
    verified: true,
  },
  {
    name: "Cheryl Mccarty",
    screen_name: "Neve",
    followers_count: 250,
    following_count: 494,
    location: "Aalbeke",
    verified: false,
  },
  {
    name: "Quyn J. Dominguez",
    screen_name: "Yoko",
    followers_count: 184,
    following_count: 852,
    location: "Máfil",
    verified: false,
  },
  {
    name: "Zachary Petersen",
    screen_name: "Stacey",
    followers_count: 357,
    following_count: 152,
    location: "Alcobendas",
    verified: false,
  },
  {
    name: "Gisela N. Macdonald",
    screen_name: "Jana",
    followers_count: 130,
    following_count: 534,
    location: "Karacabey",
    verified: true,
  },
  {
    name: "Jin Hammond",
    screen_name: "Lesley",
    followers_count: 357,
    following_count: 648,
    location: "Cartagena",
    verified: true,
  },
  {
    name: "Ashton O. Merrill",
    screen_name: "Idona",
    followers_count: 443,
    following_count: 291,
    location: "Kitscoty",
    verified: false,
  },
  {
    name: "Kyle Dotson",
    screen_name: "Bradley",
    followers_count: 384,
    following_count: 848,
    location: "Stockport",
    verified: true,
  },
  {
    name: "Justina Frazier",
    screen_name: "Kalia",
    followers_count: 273,
    following_count: 459,
    location: "Perth",
    verified: true,
  },
  {
    name: "Daphne A. Olsen",
    screen_name: "Farrah",
    followers_count: 938,
    following_count: 708,
    location: "Jackson",
    verified: true,
  },
  {
    name: "Aquila E. Jefferson",
    screen_name: "Vanna",
    followers_count: 847,
    following_count: 917,
    location: "Wardin",
    verified: true,
  },
  {
    name: "Chava S. Mullins",
    screen_name: "Preston",
    followers_count: 107,
    following_count: 850,
    location: "OugrŽe",
    verified: true,
  },
  {
    name: "Dahlia Hammond",
    screen_name: "Reed",
    followers_count: 398,
    following_count: 243,
    location: "Pemuco",
    verified: false,
  },
  {
    name: "Rae D. Velasquez",
    screen_name: "Griffith",
    followers_count: 634,
    following_count: 441,
    location: "Forchtenstein",
    verified: false,
  },
  {
    name: "Maia T. Macdonald",
    screen_name: "Chadwick",
    followers_count: 389,
    following_count: 700,
    location: "Great Falls",
    verified: false,
  },
  {
    name: "Ursa Huff",
    screen_name: "Darryl",
    followers_count: 812,
    following_count: 720,
    location: "Ciudad Madero",
    verified: true,
  },
  {
    name: "Odessa Russo",
    screen_name: "Warren",
    followers_count: 773,
    following_count: 777,
    location: "Cabildo",
    verified: true,
  },
  {
    name: "Cain Tyson",
    screen_name: "Ruby",
    followers_count: 130,
    following_count: 310,
    location: "Swan",
    verified: true,
  },
  {
    name: "Summer Boyd",
    screen_name: "Timon",
    followers_count: 446,
    following_count: 161,
    location: "La Roche-sur-Yon",
    verified: true,
  },
  {
    name: "Callum U. Ashley",
    screen_name: "Samuel",
    followers_count: 387,
    following_count: 567,
    location: "Gujranwala",
    verified: false,
  },
  {
    name: "Hunter Chambers",
    screen_name: "Belle",
    followers_count: 1000,
    following_count: 446,
    location: "Lochristi",
    verified: false,
  },
];
